### PR TITLE
fix running prettier on Windows

### PR DESCRIPTION
**Pull request by StEvUgnIn**
this commit fixed running `prettier` on other platform than Unix (e.g. Windows)

### CODE REVIEW

**Comment by trusktr** [comment]
I think without the quotes the glob will be expanded by the user's shell rather than being passed to prettier to handle consistently.

Does it work with double quotes?

**Comment by StEvUgnIn** [comment]
It was tested under Git Bash.

I can test this on my Linux container (WSL).

**Comment by ZoeDreams** [comment]
looks like it will work on my w10 machine. ill give this a test tomorrow. in the mean time @StEvUgnIn could you please rebase with master for the latest changes. sorry for the inconvenience.

**Comment by StEvUgnIn** [comment]
I'm sorry for merge, but rebase generated too many conflicts

**Review by ZoeDreams — APPROVED** [review]
tested this works on my windows 10 environment and mac

**Pull request merged**
