### PR TITLE
WIP try to import aswebglue

### PR DESCRIPTION
**Pull request by trusktr**
Not able to import aswebglue yet:

```sh
npm install
npx asc src/test.ts
```

### CODE REVIEW

**Comment by ZoeDreams** [comment]
need to make a minor change to the build script so it uses makedir module and not the actually operating systems mkdir which the -p switch breaks for windows.

**Comment by ZoeDreams** [comment]
created a temporary work around using explicit local path the the specific webgl.ts file.. not pretty but it gets the tests working and asc compiling the file again. This isn't referenced alot in the project so fixing it when AssemblyScript fixes it dynmodule source path we can update it back.

**Review by ZoeDreams — COMMENTED** [review]
working on implementing rollup to bundle a distributable to be tested against an example web app. I would like to get the build and package work flow fully working before merging this into master.

**Comment by trusktr** [comment]
@ZoeDreams thanks for this stuff! :partying_face: :tada:

**Comment by trusktr** [comment]
Oh crap, I forgot to update READMEs. :tada:

**Pull request merged**
