### PR TITLE
Add existing geometry

### PR DESCRIPTION
**Pull request by corruptedzulu**
Lots of the files are just converting things to f32. Main work was in the Geometry and Buffer classes.

### CODE REVIEW

**Comment by trusktr** [comment]
Looks like we have some conflicts here now. it's only formatting changes and assert-to-expect changes. I can help sort it out.

**Comment by corruptedzulu** [comment]
Not surprising there's conflicts. I wouldn't be surprised if there's a lot more once the other PR is merged onto this one

**Comment by trusktr** [comment]
GitHub has a bug where any PRs that were already open when we changed the build requirement to v12-v14 still expect the old builds which will never run.

**Comment by trusktr** [comment]
Good to merge!

**Pull request merged**
