### PR TITLE
convert Math.sin/Math.cos into Math.sincos calls for 1.5 to 1.8x perf improvement

### PR DESCRIPTION
**Pull request by StEvUgnIn**
this commit follows issue #45

invoke these errors: https://gist.github.com/StEvUgnIn/2ba404abe92cab0ac432cc7ed7ac7fe1

### CODE REVIEW

**Comment by ZoeDreams** [comment]
checked and works with the latest from @jtenner. nice work. thank you.

**Review by ZoeDreams — APPROVED** [review]
checked and works with the latest from @jtenner. nice work. thank you.

**Comment by ZoeDreams** [comment]
@StEvUgnIn for whatever reason github wont automerge. could you please try rebases your fork branch and updating. Sorry for the inconvenience.

**Comment by trusktr** [comment]
@ZoeDreams  Not mergeable because the branch is out of date. @StEvUgnIn you can update the branch (there's an Update button near the bottom of this page), then tests will run again, then it will be mergeable if tests pass.

Set up to be scrupulous.

**Comment by trusktr** [comment]
I went ahead and merged it for this time, but keep in mind the branches become mergeable if they are up-to-date.

**Comment by trusktr** [comment]
Thanks @StEvUgnIn !

**Comment by StEvUgnIn** [comment]
I updated it last time... this is marked by rebase...

**Comment by trusktr** [comment]
Each time any other PR is merged, then all PRs are considered out of date.

**Pull request merged**
